### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by dayue1984** [shymega/cosmo-v25-android-fw-ota#1]
Thank you!But I can not do the upodate.
The Updatepackage.zip is only 134bytes, and while cosmo reboot to update it shows error and then reboot.
My Cosmo is v23 non-rooted.

**Comment by shymega** [comment]
Please see the updated README on the repository home page. I've clarified the process.

Also, it's usually a good rule of thumb that if the OTA pkg is of that sort of size, it's not valid. I suspect you've downloaded the HTML?

**Comment by shymega** [comment]
I'll wait for you to try again, and then the issue can be closed.

**Comment by dayue1984** [comment]
It's working, my browser just downloaded a html file named .zip. Redownloaded and updated. Thank you very much!
